### ISSUE TITLE
Certificate error when running via docker-compose file locally

### ISSUE THREAD

**Issue by feveden** [markheath/globoticket-dapr#2]
Hi, When I run the solution via docker-compose file on Windows 10 machine I get the following error when starting up frontend project container:
Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
globoticket-dapr-main-frontend-1       | To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
I run the above mentioned command but to no avail. 
Could you please help me solve the problem, If you could?. Thanks.

**Comment by markheath** [comment]
it's been a while since I ran it in that configuration, so it's possibly been broken by other updates. I'll try to look at it next time I do another round of updates to this

**Comment by ikbalkazanc** [comment]
@feveden bro you can use http version. `docker-compose.override.yml`
<img width="344" alt="Screen Shot 2022-12-23 at 00 55 27" src="https://user-images.githubusercontent.com/60016655/209232709-b8d0c9db-882f-43ef-b5cb-5c6a9baf2187.png">

**Comment by jpeckham** [comment]
```
 USING DAPR
frontend-1       | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
frontend-1       |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning
frontend-1       | warn: Microsoft.AspNetCore.Hosting.Diagnostics[15]
frontend-1       |       Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'https://+:443;http://+:80'.
frontend-dapr-1  | Flag --components-path has been deprecated, use --resources-path
frontend-dapr-1  | time="2024-09-08T18:31:12.822696812Z" level=info msg="Starting Dapr Runtime -- version 1.13.0 -- commit 5980602c57e360a3354d409be516b8ffc4056fd1" app_id=frontend instance=a85d5fed914c scope=dapr.runtime type=log ver=1.13.0
frontend-dapr-1  | time="2024-09-08T18:31:12.822720041Z" level=info msg="Log level set to: info" app_id=frontend instance=a85d5fed914c scope=dapr.runtime type=log ver=1.13.0
frontend-dapr-1  | time="2024-09-08T18:31:12.8228538Z" level=warning msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=frontend instance=a85d5fed914c scope=dapr.runtime.security type=log ver=1.13.0
frontend-dapr-1  | time="2024-09-08T18:31:12.825214342Z" level=warning msg="The default value for 'spec.metric.http.increasedCardinality' will change to 'false' in Dapr 1.14" app_id=frontend instance=a85d5fed914c scope=dapr.runtime type=log ver=1.13.0
frontend-dapr-1  | time="2024-09-08T18:31:12.829115402Z" level=warning msg="A non-YAML resiliency file secrets.json was detected, it will not be loaded" app_id=frontend instance=a85d5fed914c scope=dapr.runtime type=log ver=1.13.0
frontend-1       | fail: Microsoft.Extensions.Hosting.Internal.Host[11]
frontend-1       |       Hosting failed to start
frontend-dapr-1  | time="2024-09-08T18:31:12.830010438Z" level=info msg="metrics server started on :9090/" app_id=frontend instance=a85d5fed914c scope=dapr.runtime type=log ver=1.13.0
frontend-1       |       System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
frontend-dapr-1  | time="2024-09-08T18:31:12.830062011Z" level=info msg="standalone mode configured" app_id=frontend instance=a85d5fed914c scope=dapr.runtime type=log ver=1.13.0
frontend-1       |       To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
frontend-dapr-1  | time="2024-09-08T18:31:12.83008428Z" level=info msg="app id: frontend" app_id=frontend instance=a85d5fed914c scope=dapr.runtime type=log ver=1.13.0
frontend-1       |       For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
frontend-dapr-1  | time="2024-09-08T18:31:12.830142218Z" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)" app_id=frontend instance=a85d5fed914c scope=dapr.runtime type=log ver=1.13.0
frontend-1       |          at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
frontend-1       |          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
frontend-1       |          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
frontend-1       |          at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
frontend-1       |          at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
frontend-1       |          at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
frontend-1       |          at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
frontend-1       |          at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
frontend-1       | Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
frontend-1       | To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
frontend-1       | For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
frontend-1       |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
frontend-1       |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
frontend-1       |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
frontend-1       |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
frontend-1       |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
frontend-1       |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
frontend-1       |    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
frontend-1       |    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
frontend-1       |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
frontend-1       |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
frontend-1       |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
frontend-1       |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
frontend-1       |    at Program.<Main>$(String[] args) in /src/frontend/Program.cs:line 59
```
 just adding info to the issue
